# Generated by Django 5.0.6 on 2024-11-05 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chocolate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor_suggestion', models.CharField(max_length=100)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('allergy_concerns', models.TextField(blank=True)),
                ('chocolate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='chocolate.chocolate')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('chocolate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='chocolate.chocolate')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('availability', models.CharField(max_length=50)),
                ('chocolate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_flavors', to='chocolate.chocolate')),
            ],
        ),
    ]
